# Directory where your raw sequencing reads are stored
reads_dir: "path/to/your/reads"

# Path to your reference genome
reference: "path/to/reference_genome.fasta"

# Directory for output results
output_dir: "path/to/output"

# Optional: Specify any other parameters that might be needed for various tools
trimming:
  adapter_path: "path/to/adapters.fa"
  leading: 3
  trailing: 3
  slidingwindow: "4:15"
  minlen: 36

alignment:
  threads: 4

# Add other global parameters as necessary
