# Directory where your raw sequencing reads are stored
reads_dir: "/home/cinnet/Desktop/Project_Patomatic/data"

# Path to your reference genome
reference: "/home/cinnet/Desktop/Project_Patomatic/ref/sars-cov-2_genome.fasta"

# Directory for output results
output_dir: "/home/cinnet/Desktop/Project_Patomatic/results"

# Optional: Specify any other parameters that might be needed for various tools
trimming:
  leading: 3
  trailing: 3
  slidingwindow: "4:15"
  minlen: 36

alignment:
  threads: 4

# Add other global parameters as necessary