name: patomatic_pipe
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - pip
  - python=3.8  # Specify the Python version if needed
  - fastqc=0.11.9
  - multiqc=1.9
  - trimmomatic
  - bwa
  - samtools=1.10
  - bcftools
  - quast
  - prokka
  - pip:
    - biopython==1.78

